version: '3.1'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vee
    ports:
      - "9876:5432"
    volumes:
      - vee_volume:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      NODE_ENV: development
      DB_CONNECTION_STRING: postgres://postgres:postgres@db:5432/vee
    networks:
      - app_network
    command: sh -c "npm run db:migrate && npm run start:prod"

volumes:
  vee_volume:

networks:
  app_network:
    driver: bridge